"""add image_filename to equipment

Revision ID: 2f86e40d845b
Revises: b6d4abc2fac0
Create Date: 2026-10-08 13:46:32.242578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f86e40d845b'
down_revision = 'b6d4abc2fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
