"""create equipment table model

Revision ID: 4ccb901ee23e
Revises: e0dc23214a01
Create Date: 2026-09-19 03:53:30.614521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb901ee23e'
down_revision = 'e0dc23214a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False, erver_default=sa.text('now()')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_asset_tag'), ['asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipment_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_serial_number'), ['serial_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_equipment_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_status'))
        batch_op.drop_index(batch_op.f('ix_equipment_serial_number'))
        batch_op.drop_index(batch_op.f('ix_equipment_location_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_category_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_asset_tag'))

    op.drop_table('equipment')
    # ### end Alembic commands ###
