"""add user password and role fields

Revision ID: 7489608d0d70
Revises: 54b7d77bb118
Create Date: 2026-09-24 15:21:06.682999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7489608d0d70'
down_revision = '54b7d77bb118'
branch_labels = None
depends_on = None

def upgrade():
    # Add the role column with a temporary database default.
    # This allows existing users to receive the "Employee" role.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'role',
                sa.String(length=50),
                nullable=False,
                server_default='Employee'
            )
        )

        batch_op.alter_column(
            'password_hash',
            existing_type=sa.VARCHAR(length=300),
            type_=sa.String(length=255),
            existing_nullable=False
        )

        batch_op.create_index(
            batch_op.f('ix_user_role'),
            ['role'],
            unique=False
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
