"""create department table model

Revision ID: 97be6565f6bb
Revises: 4ccb901ee23e
Create Date: 2026-09-19 04:01:56.853046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97be6565f6bb'
down_revision = '4ccb901ee23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
