"""add departments users and equipment assignments

Revision ID: c7c8986f5028
Revises: 5e51b7d9d712
Create Date: 2026-09-19 04:20:34.484610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c8986f5028'
down_revision = '5e51b7d9d712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_assignment_equipment_id'), ['equipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_assignment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_assignment_equipment_id'))

    op.drop_table('equipment_assignment')
    # ### end Alembic commands ###
